# Generated by Django 3.0.4 on 2020-04-08 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModels',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Password', models.CharField(default='12345', max_length=32)),
                ('Department', models.CharField(default=None, max_length=50)),
                ('Mail', models.EmailField(max_length=254)),
                ('Post', models.CharField(default=None, max_length=30)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=30)),
                ('Attendance', models.IntegerField(default=0)),
                ('Start_date', models.DateField(default=datetime.date(2020, 4, 9))),
                ('Salary', models.IntegerField()),
                ('Age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='live_attendance',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Department', models.CharField(default='CSE', max_length=50)),
                ('Post', models.CharField(default=None, max_length=30)),
                ('Date', models.CharField(default=datetime.date(2020, 4, 9), max_length=40)),
                ('Time', models.CharField(default='00:37:10', max_length=40)),
            ],
        ),
    ]
