# Generated by Django 3.0.4 on 2020-04-08 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facelook', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='live_attendance',
        ),
    ]
