# Generated by Django 3.0.4 on 2020-04-08 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facelook', '0002_delete_live_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='live_attendance',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Department', models.CharField(default='CSE', max_length=50)),
                ('Post', models.CharField(default=None, max_length=30)),
                ('Date', models.CharField(default=datetime.date(2020, 4, 9), max_length=40)),
                ('Time', models.CharField(default='00:46:34', max_length=40)),
            ],
        ),
    ]
